/**
 * FEC Code Generator (Feature Enable Codes)
 * For SWaP function activation on MIB2 units
 * 
 * Based on MIB2Acceso.pdf technical document
 */

export interface FECCode {
  code: string;
  nameKey: string;
  descriptionKey: string;
  category: 'connectivity' | 'performance' | 'multimedia';
}

/**
 * Predefined FEC codes for common functions
 */
export const PREDEFINED_FEC_CODES: FECCode[] = [
  {
    code: '00010001',
    nameKey: 'fec.carplay_name',
    descriptionKey: 'fec.carplay_desc',
    category: 'connectivity',
  },
  {
    code: '00010002',
    nameKey: 'fec.android_auto_name',
    descriptionKey: 'fec.android_auto_desc',
    category: 'connectivity',
  },
  {
    code: '00010004',
    nameKey: 'fec.mirrorlink_name',
    descriptionKey: 'fec.mirrorlink_desc',
    category: 'connectivity',
  },
  {
    code: '00010008',
    nameKey: 'fec.appconnect_name',
    descriptionKey: 'fec.appconnect_desc',
    category: 'connectivity',
  },
  {
    code: '00060001',
    nameKey: 'fec.perf_monitor_name',
    descriptionKey: 'fec.perf_monitor_desc',
    category: 'performance',
  },
  {
    code: '09400008',
    nameKey: 'fec.maps_europe_name',
    descriptionKey: 'fec.maps_europe_desc',
    category: 'multimedia',
  },
  {
    code: '09410008',
    nameKey: 'fec.maps_northamerica_name',
    descriptionKey: 'fec.maps_northamerica_desc',
    category: 'multimedia',
  },
];

/**
 * FEC generator online URL
 */
export const FEC_GENERATOR_URL = 'https://vwcoding.ru/en/utils/fec/';

/**
 * Generate Telnet commands for FEC code injection
 */
export function generateFecInjectionCommands(codes: string[]): string[] {
  return [
    '# Mount file system',
    'mount -uw /net/rcc/dev/shmem',
    '',
    '# Inject FEC codes',
    ...codes.map((code) => `echo "${code}" >> /net/rcc/dev/shmem/addfec.txt`),
    '',
    '# Reboot unit to apply changes',
    'reboot',
  ];
}

/**
 * Vehicle data interface
 */
export interface VehicleData {
  vin: string;  // Vehicle Identification Number
  vcrn: string; // Vehicle Component Registration Number
}

/**
 * Validate VIN format (17 alphanumeric characters)
 */
export function validateVIN(vin: string): boolean {
  const vinRegex = /^[A-HJ-NPR-Z0-9]{17}$/;
  return vinRegex.test(vin.toUpperCase());
}

/**
 * Validate VCRN format
 */
export function validateVCRN(vcrn: string): boolean {
  // VCRN is typically a unit serial number
  return vcrn.length >= 8 && vcrn.length <= 20;
}

/**
 * Error keys for FEC generation
 */
export const FEC_ERROR_KEYS = {
  invalidVin: 'fec.error_invalid_vin',
  invalidVcrn: 'fec.error_invalid_vcrn',
};

/**
 * Generate FEC code based on VIN and VCRN
 * 
 * NOTE: This is a simplified algorithm for demonstration.
 * The real VW algorithm is proprietary and more complex.
 * For production use, access to official VW database is required
 * or use tools like OBDeleven that have access to real algorithms.
 */
export function generateFECCode(vehicleData: VehicleData, featureCode: string): { code: string } | { errorKey: string } {
  const { vin, vcrn } = vehicleData;
  
  // Validate inputs
  if (!validateVIN(vin)) {
    return { errorKey: FEC_ERROR_KEYS.invalidVin };
  }
  
  if (!validateVCRN(vcrn)) {
    return { errorKey: FEC_ERROR_KEYS.invalidVcrn };
  }
  
  // Simplified algorithm (placeholder)
  // In reality, this requires VW's private key
  const vinHash = simpleHash(vin);
  const vcrnHash = simpleHash(vcrn);
  const featureHash = simpleHash(featureCode);
  
  const combinedHash = (vinHash + vcrnHash + featureHash) % 0xFFFFFFFF;
  const fecCode = combinedHash.toString(16).toUpperCase().padStart(8, '0');
  
  return { code: fecCode };
}

/**
 * Simple hash function for demonstration
 * (DO NOT use in production - for educational purposes only)
 */
function simpleHash(str: string): number {
  let hash = 0;
  for (let i = 0; i < str.length; i++) {
    const char = str.charCodeAt(i);
    hash = ((hash << 5) - hash) + char;
    hash = hash & hash; // Convert to 32bit integer
  }
  return Math.abs(hash);
}

/**
 * Generate ExceptionList.txt file content
 */
export function generateExceptionList(fecCodes: string[]): string {
  const header = `# ExceptionList.txt
# Generated by MIB2 Controller
# Date: ${new Date().toISOString()}
# 
# FEC codes:
`;

  const codes = fecCodes.map(code => `${code}`).join('\n');
  
  return header + codes + '\n';
}

/**
 * Get predefined FEC code by name key
 */
export function getPredefinedFECCode(nameKey: string): FECCode | undefined {
  return PREDEFINED_FEC_CODES.find(
    code => code.nameKey.toLowerCase() === nameKey.toLowerCase()
  );
}

/**
 * Get all FEC codes by category
 */
export function getFECCodesByCategory(category: FECCode['category']): FECCode[] {
  return PREDEFINED_FEC_CODES.filter(code => code.category === category);
}

/**
 * Validate FEC code format (8 hexadecimal digits)
 */
export function validateFECCode(code: string): boolean {
  const fecRegex = /^[0-9A-F]{8}$/i;
  return fecRegex.test(code);
}

/**
 * FEC code injection process information
 */
export const FEC_INJECTION_INFO = {
  titleKey: 'fec.injection_title',
  steps: [
    {
      step: 1,
      titleKey: 'fec.step1_title',
      descriptionKey: 'fec.step1_desc',
    },
    {
      step: 2,
      titleKey: 'fec.step2_title',
      descriptionKey: 'fec.step2_desc',
    },
    {
      step: 3,
      titleKey: 'fec.step3_title',
      descriptionKey: 'fec.step3_desc',
    },
    {
      step: 4,
      titleKey: 'fec.step4_title',
      descriptionKey: 'fec.step4_desc',
    },
    {
      step: 5,
      titleKey: 'fec.step5_title',
      descriptionKey: 'fec.step5_desc',
    },
  ],
  warningKeys: [
    'fec.warning1',
    'fec.warning2',
    'fec.warning3',
    'fec.warning4',
  ],
  technicalNoteKey: 'fec.technical_note',
};

/**
 * Generate Toolbox injection command
 */
export function generateToolboxInjectionCommand(fecCodes: string[]): string {
  return `# FEC code injection commands via MIB2 Toolbox
# Execute from Telnet (root@192.168.1.4)

# 1. Verify Toolbox is installed
ls -la /net/mmx/mnt/app/eso/hmi/lsd/jars/

# 2. Create ExceptionList.txt on SD card
cat > /media/mp000/ExceptionList.txt << EOF
${fecCodes.join('\n')}
EOF

# 3. Apply patch (from Toolbox GEM green menu)
# Select: "Patch tsd.mibstd2.system.swap"

# 4. Verify injected codes
# FEC codes will now be accepted as valid

echo "FEC codes injected successfully"
`;
}
