/**
 * MIB2 STD2 Toolbox Installation Assistant
 * Based on MIB2Acceso.pdf technical document
 */

export interface InstallationStep {
  step: number;
  titleKey: string;
  descriptionKey: string;
  command?: string;
  expectedOutput?: string;
  warningKeys?: string[];
  isOptional?: boolean;
}

/**
 * Steps for Toolbox installation via Telnet (D-Link)
 */
export const TOOLBOX_INSTALLATION_STEPS: InstallationStep[] = [
  {
    step: 1,
    titleKey: "toolbox.step1_title",
    descriptionKey: "toolbox.step1_desc",
    warningKeys: [
      "toolbox.step1_warning1",
      "toolbox.step1_warning2",
    ],
  },
  {
    step: 2,
    titleKey: "toolbox.step2_title",
    descriptionKey: "toolbox.step2_desc",
    command: `# Configure static IP: 192.168.1.10
# Subnet mask: 255.255.255.0
# Gateway: 192.168.1.1`,
  },
  {
    step: 3,
    titleKey: "toolbox.step3_title",
    descriptionKey: "toolbox.step3_desc",
    command: "ping 192.168.1.4",
    expectedOutput: "64 bytes from 192.168.1.4: icmp_seq=1 ttl=64 time=1.23 ms",
  },
  {
    step: 4,
    titleKey: "toolbox.step4_title",
    descriptionKey: "toolbox.step4_desc",
    command: "telnet 192.168.1.4 23",
    expectedOutput: `Connected to 192.168.1.4
QNX Neutrino (localhost) (pts/0)

login: `,
    warningKeys: [
      "toolbox.step4_warning1",
      "toolbox.step4_warning2",
    ],
  },
  {
    step: 5,
    titleKey: "toolbox.step5_title",
    descriptionKey: "toolbox.step5_desc",
    command: `login: root
password: root`,
    expectedOutput: "# ",
  },
  {
    step: 6,
    titleKey: "toolbox.step6_title",
    descriptionKey: "toolbox.step6_desc",
    command: `# Verify SD card mount
ls -la /media/mp000

# Verify filesystem
df -h`,
    expectedOutput: `/dev/hd0t177  /media/mp000  vfat`,
  },
  {
    step: 7,
    titleKey: "toolbox.step7_title",
    descriptionKey: "toolbox.step7_desc",
    command: `# On your PC:
# Download from: https://github.com/olli991/mib-std2-pq-zr-toolbox
# Copy install.sh to SD card root`,
    warningKeys: [
      "toolbox.step7_warning1",
      "toolbox.step7_warning2",
    ],
  },
  {
    step: 8,
    titleKey: "toolbox.step8_title",
    descriptionKey: "toolbox.step8_desc",
    command: `# Navigate to SD card
cd /media/mp000

# Set execute permissions
chmod +x install.sh

# Run installation
./install.sh`,
    expectedOutput: "MIB2 Toolbox installed successfully",
    warningKeys: [
      "toolbox.step8_warning1",
      "toolbox.step8_warning2",
    ],
  },
  {
    step: 9,
    titleKey: "toolbox.step9_title",
    descriptionKey: "toolbox.step9_desc",
    command: `# From Toolbox GEM menu:
# Select: "Patch tsd.mibstd2.system.swap"`,
    warningKeys: [
      "toolbox.step9_warning1",
      "toolbox.step9_warning2",
    ],
  },
  {
    step: 10,
    titleKey: "toolbox.step10_title",
    descriptionKey: "toolbox.step10_desc",
    command: `# Verify Toolbox files
ls -la /net/mmx/mnt/app/eso/hmi/lsd/jars/

# Search for Toolbox files
find /net/mmx -name "*toolbox*" -o -name "*mib*"`,
    expectedOutput: "Toolbox files visible in directory",
  },
  {
    step: 11,
    titleKey: "toolbox.step11_title",
    descriptionKey: "toolbox.step11_desc",
    command: "reboot",
    warningKeys: [
      "toolbox.step11_warning1",
      "toolbox.step11_warning2",
    ],
  },
];

/**
 * Alternative method: Direct eMMC access (informational only)
 */
export const EMMC_ACCESS_INFO = {
  titleKey: "toolbox.emmc_title",
  descriptionKey: "toolbox.emmc_desc",
  stepKeys: [
    "toolbox.emmc_step1",
    "toolbox.emmc_step2",
    "toolbox.emmc_step3",
    "toolbox.emmc_step4",
    "toolbox.emmc_step5",
  ],
  warningKeys: [
    "toolbox.emmc_warning1",
    "toolbox.emmc_warning2",
    "toolbox.emmc_warning3",
    "toolbox.emmc_warning4",
  ],
  technicalNoteKey: "toolbox.emmc_technical_note",
};

/**
 * Useful diagnostic commands
 */
export const DIAGNOSTIC_COMMANDS = [
  {
    nameKey: "toolbox.diag_system_info",
    command: "uname -a",
    descriptionKey: "toolbox.diag_system_info_desc",
  },
  {
    nameKey: "toolbox.diag_firmware_version",
    command: "cat /net/mmx/fs/sda0/VERSION",
    descriptionKey: "toolbox.diag_firmware_version_desc",
  },
  {
    nameKey: "toolbox.diag_processes",
    command: "ps aux",
    descriptionKey: "toolbox.diag_processes_desc",
  },
  {
    nameKey: "toolbox.diag_disk_space",
    command: "df -h",
    descriptionKey: "toolbox.diag_disk_space_desc",
  },
  {
    nameKey: "toolbox.diag_network",
    command: "ifconfig -a",
    descriptionKey: "toolbox.diag_network_desc",
  },
  {
    nameKey: "toolbox.diag_services",
    command: "netstat -an | grep LISTEN",
    descriptionKey: "toolbox.diag_services_desc",
  },
  {
    nameKey: "toolbox.diag_hardware",
    command: "pidin info",
    descriptionKey: "toolbox.diag_hardware_desc",
  },
];

/**
 * Generate complete installation script
 */
export function generateInstallationScript(): string {
  return `#!/bin/sh
# MIB2 STD2 Toolbox Installation Script
# Generated by MIB2 Controller
# Date: ${new Date().toISOString()}

echo "=== MIB2 STD2 Toolbox Installation ==="
echo ""

# Verify root access
if [ "$(whoami)" != "root" ]; then
    echo "ERROR: This script must be run as root"
    exit 1
fi

# Verify SD card mount
echo "Verifying SD card..."
if [ ! -d "/media/mp000" ]; then
    echo "ERROR: SD card not mounted at /media/mp000"
    exit 1
fi

# Verify Toolbox install.sh exists
if [ ! -f "/media/mp000/install.sh" ]; then
    echo "ERROR: install.sh not found on SD card"
    echo "Download Toolbox from: https://github.com/olli991/mib-std2-pq-zr-toolbox"
    exit 1
fi

# Run Toolbox installation
echo "Running Toolbox installation..."
cd /media/mp000
chmod +x install.sh
./install.sh

# Verify installation
echo ""
echo "Verifying installation..."
if [ -d "/net/mmx/mnt/app/eso/hmi/lsd/jars/" ]; then
    echo "OK Toolbox installed successfully"
    echo ""
    echo "Next steps:"
    echo "1. Reboot MIB2 unit"
    echo "2. Access Toolbox GEM menu"
    echo "3. Run 'Patch tsd.mibstd2.system.swap'"
    echo "4. Create ExceptionList.txt with desired FEC codes"
else
    echo "ERROR Installation failed"
    exit 1
fi

echo ""
echo "=== Installation completed ==="
`;
}

/**
 * Validate Toolbox installation
 */
export function generateToolboxVerificationCommand(): string {
  return `# Verify MIB2 Toolbox installation
echo "Verifying Toolbox installation..."

# Search for Toolbox files
if [ -d "/net/mmx/mnt/app/eso/hmi/lsd/jars/" ]; then
    echo "OK Toolbox directory found"
    ls -la /net/mmx/mnt/app/eso/hmi/lsd/jars/ | grep -i toolbox
else
    echo "ERROR Toolbox not installed"
fi

# Check if system is patched
if [ -f "/media/mp000/ExceptionList.txt" ]; then
    echo "OK ExceptionList.txt found"
    cat /media/mp000/ExceptionList.txt
else
    echo "INFO ExceptionList.txt not found (system not patched)"
fi
`;
}
