#!/usr/bin/env python3
"""
Agregar TODAS las claves de traducción faltantes
"""

import json
import os

LOCALES_DIR = "/home/ubuntu/mib2_controller/locales"

# Todas las traducciones faltantes
TRANSLATIONS = {
    "auto_spoof": {
        "es": {
            "chipset": "Chipset",
            "compatible": "Compatible",
            "connect_compatible_adapter": "Conecta un adaptador compatible",
            "connected_device": "Dispositivo Conectado",
            "current_vid_pid": "VID/PID Actual",
            "detect_now": "Detectar Ahora",
            "detecting_eeprom_message": "Se analizará la EEPROM del adaptador para determinar si es modificable. Este proceso es seguro y no modifica nada.",
            "detecting_eeprom_title": "🔍 Detectando Tipo de EEPROM",
            "detection_error": "Error de Detección",
            "detection_error_message": "No se pudo detectar el tipo de EEPROM: {{error}}",
            "device_not_compatible": "Dispositivo No Compatible",
            "device_not_detected_message": "No se detectó ningún adaptador USB. Conecta un adaptador ASIX compatible y vuelve a intentar.",
            "device_not_detected_title": "⚠️ Dispositivo No Detectado",
            "eeprom_detected": "✅ EEPROM Externa Detectada",
            "eeprom_detected_message": "Se detectó una EEPROM {{type}} modificable. ¿Deseas continuar con el spoofing?",
            "error_not_compatible": "El adaptador no es compatible con MIB2",
            "error_unknown": "Error desconocido durante el spoofing",
            "error_verification_failed": "La verificación del spoofing falló",
            "execute_auto_spoof": "Ejecutar Auto-Spoof",
            "executing": "Ejecutando...",
            "force_no_verification": "Forzar (Sin Verificación)",
            "force_no_verification_desc": "Ejecuta el spoofing sin verificar el resultado. Usar solo si el método normal falla.",
            "name": "Nombre",
            "no_cancel": "No, Cancelar",
            "no_device_connected": "No hay dispositivo conectado",
            "quick_spoof": "⚡ Spoof Rápido",
            "quick_spoof_desc": "Ejecuta el spoofing sin confirmaciones adicionales. Solo para usuarios experimentados.",
            "quick_spoof_message": "Se ejecutará el spoofing directamente sin verificación de EEPROM. ¿Continuar?",
            "quick_spoof_title": "⚠️ Spoof Rápido",
            "reconnect_instructions": "Desconecta y reconecta el adaptador para aplicar los cambios.",
            "share_dialog_title": "Compartir Resultado",
            "share_text": "Resultado del spoofing USB",
            "spoofing_blocked": "❌ Spoofing Bloqueado",
            "spoofing_blocked_message": "Se detectó una {{type}}. Razón: {{reason}}. El spoofing no es posible en este adaptador.",
            "step_creating_backup": "Creando backup de EEPROM...",
            "step_error": "Error",
            "step_idle": "Esperando",
            "step_success": "Completado",
            "step_validating": "Validando cambios...",
            "step_verifying": "Verificando escritura...",
            "step_writing_pid_high": "Escribiendo PID (byte alto)...",
            "step_writing_pid_low": "Escribiendo PID (byte bajo)...",
            "step_writing_vid_high": "Escribiendo VID (byte alto)...",
            "step_writing_vid_low": "Escribiendo VID (byte bajo)...",
            "subtitle": "Modificar VID/PID del adaptador USB",
            "success_message": "El spoofing se completó exitosamente. El adaptador ahora tiene el VID/PID de MIB2.",
            "target_values": "Valores Objetivo",
            "test_fail_message": "El test de spoofing falló. El adaptador puede no ser compatible.",
            "test_fail_title": "⚠️ Spoofing No Detectado",
            "test_spoofing": "🧪 Test de Spoofing",
            "test_spoofing_desc": "Verifica si el adaptador puede ser modificado sin realizar cambios permanentes.",
            "test_success_message": "El test fue exitoso. El adaptador es compatible con el spoofing.",
            "test_success_title": "✅ Spoofing Exitoso",
            "testing": "Probando...",
            "verification_skipped_note": "Nota: La verificación fue omitida. Desconecta y reconecta el adaptador para confirmar.",
            "with_triple_confirmation": "Con Triple Confirmación",
            "yes_execute": "Sí, Ejecutar"
        },
        "en": {
            "chipset": "Chipset",
            "compatible": "Compatible",
            "connect_compatible_adapter": "Connect a compatible adapter",
            "connected_device": "Connected Device",
            "current_vid_pid": "Current VID/PID",
            "detect_now": "Detect Now",
            "detecting_eeprom_message": "The adapter's EEPROM will be analyzed to determine if it's modifiable. This process is safe and doesn't modify anything.",
            "detecting_eeprom_title": "🔍 Detecting EEPROM Type",
            "detection_error": "Detection Error",
            "detection_error_message": "Could not detect EEPROM type: {{error}}",
            "device_not_compatible": "Device Not Compatible",
            "device_not_detected_message": "No USB adapter detected. Connect a compatible ASIX adapter and try again.",
            "device_not_detected_title": "⚠️ Device Not Detected",
            "eeprom_detected": "✅ External EEPROM Detected",
            "eeprom_detected_message": "A modifiable {{type}} EEPROM was detected. Do you want to continue with spoofing?",
            "error_not_compatible": "The adapter is not compatible with MIB2",
            "error_unknown": "Unknown error during spoofing",
            "error_verification_failed": "Spoofing verification failed",
            "execute_auto_spoof": "Execute Auto-Spoof",
            "executing": "Executing...",
            "force_no_verification": "Force (No Verification)",
            "force_no_verification_desc": "Execute spoofing without verifying the result. Use only if normal method fails.",
            "name": "Name",
            "no_cancel": "No, Cancel",
            "no_device_connected": "No device connected",
            "quick_spoof": "⚡ Quick Spoof",
            "quick_spoof_desc": "Execute spoofing without additional confirmations. For experienced users only.",
            "quick_spoof_message": "Spoofing will be executed directly without EEPROM verification. Continue?",
            "quick_spoof_title": "⚠️ Quick Spoof",
            "reconnect_instructions": "Disconnect and reconnect the adapter to apply changes.",
            "share_dialog_title": "Share Result",
            "share_text": "USB spoofing result",
            "spoofing_blocked": "❌ Spoofing Blocked",
            "spoofing_blocked_message": "A {{type}} was detected. Reason: {{reason}}. Spoofing is not possible on this adapter.",
            "step_creating_backup": "Creating EEPROM backup...",
            "step_error": "Error",
            "step_idle": "Waiting",
            "step_success": "Completed",
            "step_validating": "Validating changes...",
            "step_verifying": "Verifying write...",
            "step_writing_pid_high": "Writing PID (high byte)...",
            "step_writing_pid_low": "Writing PID (low byte)...",
            "step_writing_vid_high": "Writing VID (high byte)...",
            "step_writing_vid_low": "Writing VID (low byte)...",
            "subtitle": "Modify USB adapter VID/PID",
            "success_message": "Spoofing completed successfully. The adapter now has the MIB2 VID/PID.",
            "target_values": "Target Values",
            "test_fail_message": "Spoofing test failed. The adapter may not be compatible.",
            "test_fail_title": "⚠️ Spoofing Not Detected",
            "test_spoofing": "🧪 Spoofing Test",
            "test_spoofing_desc": "Verify if the adapter can be modified without making permanent changes.",
            "test_success_message": "Test was successful. The adapter is compatible with spoofing.",
            "test_success_title": "✅ Spoofing Successful",
            "testing": "Testing...",
            "verification_skipped_note": "Note: Verification was skipped. Disconnect and reconnect the adapter to confirm.",
            "with_triple_confirmation": "With Triple Confirmation",
            "yes_execute": "Yes, Execute"
        },
        "de": {
            "chipset": "Chipsatz",
            "compatible": "Kompatibel",
            "connect_compatible_adapter": "Kompatiblen Adapter anschließen",
            "connected_device": "Verbundenes Gerät",
            "current_vid_pid": "Aktuelle VID/PID",
            "detect_now": "Jetzt erkennen",
            "detecting_eeprom_message": "Das EEPROM des Adapters wird analysiert, um festzustellen, ob es modifizierbar ist. Dieser Vorgang ist sicher und ändert nichts.",
            "detecting_eeprom_title": "🔍 EEPROM-Typ erkennen",
            "detection_error": "Erkennungsfehler",
            "detection_error_message": "EEPROM-Typ konnte nicht erkannt werden: {{error}}",
            "device_not_compatible": "Gerät nicht kompatibel",
            "device_not_detected_message": "Kein USB-Adapter erkannt. Schließen Sie einen kompatiblen ASIX-Adapter an und versuchen Sie es erneut.",
            "device_not_detected_title": "⚠️ Gerät nicht erkannt",
            "eeprom_detected": "✅ Externes EEPROM erkannt",
            "eeprom_detected_message": "Ein modifizierbares {{type}} EEPROM wurde erkannt. Möchten Sie mit dem Spoofing fortfahren?",
            "error_not_compatible": "Der Adapter ist nicht mit MIB2 kompatibel",
            "error_unknown": "Unbekannter Fehler beim Spoofing",
            "error_verification_failed": "Spoofing-Verifizierung fehlgeschlagen",
            "execute_auto_spoof": "Auto-Spoof ausführen",
            "executing": "Wird ausgeführt...",
            "force_no_verification": "Erzwingen (Ohne Verifizierung)",
            "force_no_verification_desc": "Spoofing ohne Ergebnisverifizierung ausführen. Nur verwenden, wenn die normale Methode fehlschlägt.",
            "name": "Name",
            "no_cancel": "Nein, Abbrechen",
            "no_device_connected": "Kein Gerät verbunden",
            "quick_spoof": "⚡ Schnell-Spoof",
            "quick_spoof_desc": "Spoofing ohne zusätzliche Bestätigungen ausführen. Nur für erfahrene Benutzer.",
            "quick_spoof_message": "Spoofing wird direkt ohne EEPROM-Verifizierung ausgeführt. Fortfahren?",
            "quick_spoof_title": "⚠️ Schnell-Spoof",
            "reconnect_instructions": "Trennen und verbinden Sie den Adapter erneut, um die Änderungen anzuwenden.",
            "share_dialog_title": "Ergebnis teilen",
            "share_text": "USB-Spoofing-Ergebnis",
            "spoofing_blocked": "❌ Spoofing blockiert",
            "spoofing_blocked_message": "Ein {{type}} wurde erkannt. Grund: {{reason}}. Spoofing ist auf diesem Adapter nicht möglich.",
            "step_creating_backup": "EEPROM-Backup wird erstellt...",
            "step_error": "Fehler",
            "step_idle": "Warten",
            "step_success": "Abgeschlossen",
            "step_validating": "Änderungen werden validiert...",
            "step_verifying": "Schreibvorgang wird verifiziert...",
            "step_writing_pid_high": "PID wird geschrieben (High-Byte)...",
            "step_writing_pid_low": "PID wird geschrieben (Low-Byte)...",
            "step_writing_vid_high": "VID wird geschrieben (High-Byte)...",
            "step_writing_vid_low": "VID wird geschrieben (Low-Byte)...",
            "subtitle": "USB-Adapter VID/PID ändern",
            "success_message": "Spoofing erfolgreich abgeschlossen. Der Adapter hat jetzt die MIB2 VID/PID.",
            "target_values": "Zielwerte",
            "test_fail_message": "Spoofing-Test fehlgeschlagen. Der Adapter ist möglicherweise nicht kompatibel.",
            "test_fail_title": "⚠️ Spoofing nicht erkannt",
            "test_spoofing": "🧪 Spoofing-Test",
            "test_spoofing_desc": "Prüfen, ob der Adapter ohne dauerhafte Änderungen modifiziert werden kann.",
            "test_success_message": "Test war erfolgreich. Der Adapter ist mit Spoofing kompatibel.",
            "test_success_title": "✅ Spoofing erfolgreich",
            "testing": "Wird getestet...",
            "verification_skipped_note": "Hinweis: Verifizierung wurde übersprungen. Trennen und verbinden Sie den Adapter erneut zur Bestätigung.",
            "with_triple_confirmation": "Mit dreifacher Bestätigung",
            "yes_execute": "Ja, Ausführen"
        }
    },
    "commands": {
        "es": {
            "clear": "Limpiar",
            "connect": "Conectar",
            "connect_first": "Conectar Primero",
            "connect_first_to_send": "Conéctate primero para enviar comandos",
            "connecting": "Conectando...",
            "disconnect": "Desconectar",
            "send": "Enviar",
            "terminal_empty": "Terminal vacía",
            "type_command": "Escribe un comando...",
            "type_command_below": "Escribe un comando abajo"
        },
        "en": {
            "clear": "Clear",
            "connect": "Connect",
            "connect_first": "Connect First",
            "connect_first_to_send": "Connect first to send commands",
            "connecting": "Connecting...",
            "disconnect": "Disconnect",
            "send": "Send",
            "terminal_empty": "Terminal empty",
            "type_command": "Type a command...",
            "type_command_below": "Type a command below"
        },
        "de": {
            "clear": "Löschen",
            "connect": "Verbinden",
            "connect_first": "Zuerst verbinden",
            "connect_first_to_send": "Zuerst verbinden, um Befehle zu senden",
            "connecting": "Verbinden...",
            "disconnect": "Trennen",
            "send": "Senden",
            "terminal_empty": "Terminal leer",
            "type_command": "Befehl eingeben...",
            "type_command_below": "Befehl unten eingeben"
        }
    },
    "common": {
        "es": {
            "unknown": "Desconocido"
        },
        "en": {
            "unknown": "Unknown"
        },
        "de": {
            "unknown": "Unbekannt"
        }
    },
    "diag": {
        "es": {
            "all": "Todos",
            "auto": "Auto",
            "clear": "Limpiar",
            "clear_logs_confirm": "¿Estás seguro de que deseas eliminar todos los logs?",
            "clear_logs_title": "Limpiar Logs",
            "errors": "Errores",
            "export": "Exportar",
            "logs_exported": "Logs Exportados",
            "logs_exported_message": "Los logs han sido exportados correctamente",
            "manual": "Manual",
            "no_logs_of_type": "No hay logs de este tipo",
            "no_logs_yet": "No hay logs aún",
            "share_logs": "Compartir Logs",
            "subtitle": "Logs del sistema y diagnósticos",
            "successes": "Éxitos",
            "warnings": "Advertencias"
        },
        "en": {
            "all": "All",
            "auto": "Auto",
            "clear": "Clear",
            "clear_logs_confirm": "Are you sure you want to delete all logs?",
            "clear_logs_title": "Clear Logs",
            "errors": "Errors",
            "export": "Export",
            "logs_exported": "Logs Exported",
            "logs_exported_message": "Logs have been exported successfully",
            "manual": "Manual",
            "no_logs_of_type": "No logs of this type",
            "no_logs_yet": "No logs yet",
            "share_logs": "Share Logs",
            "subtitle": "System logs and diagnostics",
            "successes": "Successes",
            "warnings": "Warnings"
        },
        "de": {
            "all": "Alle",
            "auto": "Auto",
            "clear": "Löschen",
            "clear_logs_confirm": "Sind Sie sicher, dass Sie alle Logs löschen möchten?",
            "clear_logs_title": "Logs löschen",
            "errors": "Fehler",
            "export": "Exportieren",
            "logs_exported": "Logs exportiert",
            "logs_exported_message": "Logs wurden erfolgreich exportiert",
            "manual": "Manuell",
            "no_logs_of_type": "Keine Logs dieses Typs",
            "no_logs_yet": "Noch keine Logs",
            "share_logs": "Logs teilen",
            "subtitle": "Systemprotokolle und Diagnose",
            "successes": "Erfolge",
            "warnings": "Warnungen"
        }
    },
    "usb": {
        "es": {
            "active": "Activo",
            "adapter": "Adaptador",
            "backup_created": "Backup Creado",
            "backup_created_message": "El backup de EEPROM se ha creado correctamente",
            "backup_desc": "Crear copia de seguridad de la EEPROM",
            "backup_error": "Error de Backup",
            "backup_error_message": "No se pudo crear el backup: {{error}}",
            "chipset_confirmed": "Chipset confirmado",
            "chipset_experimental": "Chipset experimental",
            "connect": "Conectar",
            "connect_adapter": "Conecta un adaptador USB",
            "connect_error": "Error de Conexión",
            "connect_error_message": "No se pudo conectar al dispositivo: {{error}}",
            "connected": "Conectado",
            "connected_message": "Dispositivo conectado correctamente",
            "connecting": "Conectando...",
            "connection_status": "Estado de Conexión",
            "connection_time": "Tiempo de Conexión",
            "could_not_open": "No se pudo abrir el dispositivo",
            "create_backup": "Crear Backup",
            "create_backup_manual": "Crear backup manual",
            "create_backup_message": "Se creará una copia de seguridad de la EEPROM actual",
            "create_backup_title": "Crear Backup de EEPROM",
            "creating_backup": "Creando backup...",
            "detected_profile": "Perfil Detectado",
            "device_info": "Información del Dispositivo",
            "devices_detected": "Dispositivos Detectados",
            "disconnect": "Desconectar",
            "disconnect_confirm": "¿Deseas desconectar el dispositivo?",
            "disconnect_desc": "Desconectar adaptador USB",
            "disconnect_error": "Error de Desconexión",
            "disconnect_error_message": "No se pudo desconectar: {{error}}",
            "disconnect_title": "Desconectar Dispositivo",
            "eeprom_external": "EEPROM Externa",
            "go_to_auto_spoof": "Ir a Auto-Spoof",
            "mib2_compatible": "Compatible con MIB2",
            "name": "Nombre",
            "no_devices": "Sin Dispositivos",
            "not_compatible_recommend": "No compatible - Se recomienda otro adaptador",
            "permissions_denied": "Permisos denegados",
            "realtime_info": "Información en Tiempo Real",
            "recommended_spoofing": "Spoofing recomendado",
            "refresh_devices": "Actualizar Dispositivos",
            "request_permissions": "Solicitar Permisos",
            "scan_now": "Escanear Ahora",
            "scanning": "Escaneando...",
            "serial": "Serial",
            "service_status": "Estado del Servicio",
            "statistics": "Estadísticas",
            "target_profile": "Perfil Objetivo",
            "test_eeprom": "Test de EEPROM",
            "test_eeprom_desc": "Verificar estado de la EEPROM",
            "test_eeprom_error": "Error de Test",
            "test_eeprom_error_message": "No se pudo realizar el test: {{error}}",
            "testing": "Probando...",
            "tip_1": "Usa un cable OTG de calidad",
            "tip_2": "Algunos adaptadores requieren alimentación externa",
            "tip_3": "Si no detecta, desconecta y reconecta",
            "tip_4": "Verifica que el adaptador sea ASIX compatible",
            "tips": "Consejos",
            "unknown": "Desconocido"
        },
        "en": {
            "active": "Active",
            "adapter": "Adapter",
            "backup_created": "Backup Created",
            "backup_created_message": "EEPROM backup has been created successfully",
            "backup_desc": "Create EEPROM backup",
            "backup_error": "Backup Error",
            "backup_error_message": "Could not create backup: {{error}}",
            "chipset_confirmed": "Chipset confirmed",
            "chipset_experimental": "Experimental chipset",
            "connect": "Connect",
            "connect_adapter": "Connect a USB adapter",
            "connect_error": "Connection Error",
            "connect_error_message": "Could not connect to device: {{error}}",
            "connected": "Connected",
            "connected_message": "Device connected successfully",
            "connecting": "Connecting...",
            "connection_status": "Connection Status",
            "connection_time": "Connection Time",
            "could_not_open": "Could not open device",
            "create_backup": "Create Backup",
            "create_backup_manual": "Create manual backup",
            "create_backup_message": "A backup of the current EEPROM will be created",
            "create_backup_title": "Create EEPROM Backup",
            "creating_backup": "Creating backup...",
            "detected_profile": "Detected Profile",
            "device_info": "Device Information",
            "devices_detected": "Devices Detected",
            "disconnect": "Disconnect",
            "disconnect_confirm": "Do you want to disconnect the device?",
            "disconnect_desc": "Disconnect USB adapter",
            "disconnect_error": "Disconnection Error",
            "disconnect_error_message": "Could not disconnect: {{error}}",
            "disconnect_title": "Disconnect Device",
            "eeprom_external": "External EEPROM",
            "go_to_auto_spoof": "Go to Auto-Spoof",
            "mib2_compatible": "MIB2 Compatible",
            "name": "Name",
            "no_devices": "No Devices",
            "not_compatible_recommend": "Not compatible - Another adapter recommended",
            "permissions_denied": "Permissions denied",
            "realtime_info": "Real-time Information",
            "recommended_spoofing": "Spoofing recommended",
            "refresh_devices": "Refresh Devices",
            "request_permissions": "Request Permissions",
            "scan_now": "Scan Now",
            "scanning": "Scanning...",
            "serial": "Serial",
            "service_status": "Service Status",
            "statistics": "Statistics",
            "target_profile": "Target Profile",
            "test_eeprom": "EEPROM Test",
            "test_eeprom_desc": "Verify EEPROM status",
            "test_eeprom_error": "Test Error",
            "test_eeprom_error_message": "Could not perform test: {{error}}",
            "testing": "Testing...",
            "tip_1": "Use a quality OTG cable",
            "tip_2": "Some adapters require external power",
            "tip_3": "If not detected, disconnect and reconnect",
            "tip_4": "Verify the adapter is ASIX compatible",
            "tips": "Tips",
            "unknown": "Unknown"
        },
        "de": {
            "active": "Aktiv",
            "adapter": "Adapter",
            "backup_created": "Backup erstellt",
            "backup_created_message": "EEPROM-Backup wurde erfolgreich erstellt",
            "backup_desc": "EEPROM-Backup erstellen",
            "backup_error": "Backup-Fehler",
            "backup_error_message": "Backup konnte nicht erstellt werden: {{error}}",
            "chipset_confirmed": "Chipsatz bestätigt",
            "chipset_experimental": "Experimenteller Chipsatz",
            "connect": "Verbinden",
            "connect_adapter": "USB-Adapter anschließen",
            "connect_error": "Verbindungsfehler",
            "connect_error_message": "Verbindung zum Gerät nicht möglich: {{error}}",
            "connected": "Verbunden",
            "connected_message": "Gerät erfolgreich verbunden",
            "connecting": "Verbinden...",
            "connection_status": "Verbindungsstatus",
            "connection_time": "Verbindungszeit",
            "could_not_open": "Gerät konnte nicht geöffnet werden",
            "create_backup": "Backup erstellen",
            "create_backup_manual": "Manuelles Backup erstellen",
            "create_backup_message": "Ein Backup des aktuellen EEPROM wird erstellt",
            "create_backup_title": "EEPROM-Backup erstellen",
            "creating_backup": "Backup wird erstellt...",
            "detected_profile": "Erkanntes Profil",
            "device_info": "Geräteinformationen",
            "devices_detected": "Erkannte Geräte",
            "disconnect": "Trennen",
            "disconnect_confirm": "Möchten Sie das Gerät trennen?",
            "disconnect_desc": "USB-Adapter trennen",
            "disconnect_error": "Trennungsfehler",
            "disconnect_error_message": "Trennung nicht möglich: {{error}}",
            "disconnect_title": "Gerät trennen",
            "eeprom_external": "Externes EEPROM",
            "go_to_auto_spoof": "Zu Auto-Spoof gehen",
            "mib2_compatible": "MIB2-kompatibel",
            "name": "Name",
            "no_devices": "Keine Geräte",
            "not_compatible_recommend": "Nicht kompatibel - Anderer Adapter empfohlen",
            "permissions_denied": "Berechtigungen verweigert",
            "realtime_info": "Echtzeit-Informationen",
            "recommended_spoofing": "Spoofing empfohlen",
            "refresh_devices": "Geräte aktualisieren",
            "request_permissions": "Berechtigungen anfordern",
            "scan_now": "Jetzt scannen",
            "scanning": "Scannen...",
            "serial": "Seriennummer",
            "service_status": "Dienststatus",
            "statistics": "Statistiken",
            "target_profile": "Zielprofil",
            "test_eeprom": "EEPROM-Test",
            "test_eeprom_desc": "EEPROM-Status überprüfen",
            "test_eeprom_error": "Testfehler",
            "test_eeprom_error_message": "Test konnte nicht durchgeführt werden: {{error}}",
            "testing": "Wird getestet...",
            "tip_1": "Verwenden Sie ein hochwertiges OTG-Kabel",
            "tip_2": "Einige Adapter benötigen externe Stromversorgung",
            "tip_3": "Wenn nicht erkannt, trennen und erneut verbinden",
            "tip_4": "Überprüfen Sie, ob der Adapter ASIX-kompatibel ist",
            "tips": "Tipps",
            "unknown": "Unbekannt"
        }
    }
}

def deep_merge(base: dict, updates: dict) -> dict:
    """Merge updates into base recursively"""
    result = base.copy()
    for key, value in updates.items():
        if key in result and isinstance(result[key], dict) and isinstance(value, dict):
            result[key] = deep_merge(result[key], value)
        else:
            result[key] = value
    return result

def update_locale_file(lang: str):
    """Update a locale file with new translations"""
    filepath = os.path.join(LOCALES_DIR, f"{lang}.json")
    
    # Read existing file
    with open(filepath, 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    # Add new translations
    for section, translations in TRANSLATIONS.items():
        if lang in translations:
            if section not in data:
                data[section] = {}
            data[section] = deep_merge(data[section], translations[lang])
    
    # Write back
    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    
    print(f"Updated {filepath}")

def main():
    for lang in ['es', 'en', 'de']:
        update_locale_file(lang)
    print("\n✅ All missing translations added!")

if __name__ == "__main__":
    main()
